In [1]:
# import libraries
import pandas as pd
import numpy as np

In [2]:
# Import Classes from sklearn.preprocessing
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer

In [3]:
df = pd.read_csv('covid_toy.csv')

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
# count_values()
df['city'].value_counts()
# check for column null values
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
# import train_test_split from sklearn.model_selection
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']),
                                                            df['has_covid'],
                                                           test_size=0.2,
                                                           random_state=0)

In [7]:
X_train

    age  gender  fever   cough       city
43   22  Female   99.0    Mild  Bangalore
62   56  Female  104.0  Strong  Bangalore
3    31  Female   98.0    Mild    Kolkata
71   75  Female  104.0  Strong      Delhi
45   72    Male   99.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
96   51  Female  101.0  Strong    Kolkata
67   65    Male   99.0    Mild  Bangalore
64   42    Male  104.0    Mild     Mumbai
47   18  Female  104.0    Mild  Bangalore
44   20    Male  102.0  Strong      Delhi

[80 rows x 5 columns]

# 1.  Aam Zindagi

In [8]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# Also test the data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [9]:
# ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# Also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [10]:
# OneHotEncoding --> gender, city
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [11]:
# Extracing age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# Also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [12]:
# train dataset
X_train_transformed = np.concatenate((X_train_age, X_train_fever, X_train_gender_city, X_train_cough), axis=1)
# also with test dataset
X_test_transformed = np.concatenate((X_test_age, X_test_fever, X_test_gender_city, X_test_cough), axis=1)

X_train_transformed.shape
pd.DataFrame(X_train_transformed).astype(dtype=np.int32)

     0    1  2  3  4  5  6
0   22   99  0  0  0  0  0
1   56  104  0  0  0  0  1
2   31   98  0  0  1  0  0
3   75  104  0  1  0  0  1
4   72   99  1  0  0  0  0
..  ..  ... .. .. .. .. ..
75  51  101  0  0  1  0  1
76  65   99  1  0  0  0  0
77  42  104  1  0  0  1  0
78  18  104  0  0  0  0  0
79  20  102  1  1  0  0  1

[80 rows x 7 columns]

In [24]:
# Mentos Zindagi
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(sparse_output=False, drop='first'),['gender', 'city'])
], remainder='passthrough')

# fit and transform
pd.DataFrame(transformer.fit_transform(X_train)).astype(dtype=np.int32)

      0  1  2  3  4  5   6
0    99  0  0  0  0  0  22
1   104  1  0  0  0  0  56
2    98  0  0  0  1  0  31
3   104  1  0  1  0  0  75
4    99  0  1  0  0  0  72
..  ... .. .. .. .. ..  ..
75  101  1  0  0  1  0  51
76   99  0  1  0  0  0  65
77  104  0  1  0  0  1  42
78  104  0  0  0  0  0  18
79  102  1  1  1  0  0  20

[80 rows x 7 columns]