In [11]:
# import pandas
import pandas as pd
# import numpy
import numpy as np

In [26]:
# import requests
import requests

url = "https://api.themoviedb.org/3/movie/top_rated"
headers = {
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwNWM3NWY1MjNkYzYyZmFiNzVhNjJmYTc1MGM1NWEzMSIsIm5iZiI6MTc3MDM5MzIzMy42Mywic3ViIjoiNjk4NjBlOTFmMmU5NzU0YWI0NDhkZTJiIiwic2NvcGVzIjpbImFwaV9yZWFkIl0sInZlcnNpb24iOjF9.xze-JgRv5x5MhGWkMknwVIKVy_0vBD1-byIpdfI5f2I"
}

response = requests.get(url, headers=headers)
# Get Data
data = response.json()

In [126]:
# Let Convert it into the DataFrame()
movies = data['results']
# DataGFrame
pd.DataFrame(movies)

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/c4sKPgyJj19GBCAvUjpPRiiA45.jpg,"[35, 53]",276839,en,Home Sweet Hell,"Don Champagne seems to have it all, but when h...",0.9817,/a0S1ou77hJ8RAxGkpyZGbfUr2SG.jpg,2015-03-13,Home Sweet Hell,False,5.424,489
1,False,/mT26Lktm0paarsL2Au2VlOLJICh.jpg,"[27, 35]",10012,en,Cursed,A werewolf loose in Los Angeles changes the li...,2.8784,/em45jL4CfTMyj5V83kj7rhdorJu.jpg,2005-02-25,Cursed,False,5.424,756
2,False,/264UPQQm6cIF3NwXQDrj8W6e7K8.jpg,"[12, 10751, 35, 14]",39346,en,Casper: A Spirited Beginning,Before he met and befriended the other ghouls ...,0.8964,/qq3K8HnVa8VEdFWUun0ngvfa19h.jpg,1997-09-09,Casper: A Spirited Beginning,False,5.400,330
3,False,/xdH8k2O6mpLv4szeLkQGiM1aSOC.jpg,"[12, 10751, 10770, 878, 14]",10372,en,Ewoks: The Battle for Endor,"The army of the Marauders, led by King Terak a...",1.9489,/ntgKdekb7xMKscyh2Hei706LBLf.jpg,1985-11-24,Ewoks: The Battle for Endor,False,5.423,339
4,False,/aVgqxRQ8M8aJnfO1eUZEmNJSTxm.jpg,"[28, 12, 35]",9838,en,King Solomon's Mines,"Ever in search of adventure, explorer Allan Qu...",1.1096,/kpaW2gh0hjMPwoz30JL3gRKi2Ho.jpg,1985-11-22,King Solomon's Mines,False,5.423,452
5,False,/nr5smF4avc77lhWHNcGLF7guXv1.jpg,"[27, 9648]",465086,en,The Grudge,After a young mother murders her family in her...,2.2469,/vN7JHlHOT9rHNDU27tfYqhABBj5.jpg,2019-12-31,The Grudge,False,5.422,1294
6,False,/iV8jui6eHwaj93NJqGPd8O3UuHf.jpg,"[35, 18, 10749]",413471,en,The Late Bloomer,A sex therapist goes through puberty after the...,0.7164,/al9PDW3lxsDGNnphpVWdO9GvSGU.jpg,2016-10-07,The Late Bloomer,False,5.422,353
7,False,/oEH2tn8G1YGEhNBVqSAW6k1C9iB.jpg,[35],12657,en,Soul Plane,Following a ridiculously awful flight that lea...,2.0001,/b5Rzb5JUwPinllWGYUYER3OV14F.jpg,2004-05-28,Soul Plane,False,5.422,481
8,False,/o2iN9n2ShVqobqnYR0odM6yIlgW.jpg,"[53, 27]",203834,en,Jessabelle,A young woman recuperating at her father's run...,4.6699,/9WP1ADKCeDG0avA0WSo4mUemTqW.jpg,2014-11-07,Jessabelle,False,5.400,841
9,False,/mYsUWQoOYme8T6OELieOuHM08PH.jpg,"[27, 53]",10160,en,A Nightmare on Elm Street: The Dream Child,The pregnant Alice finds Freddy Krueger striki...,2.4982,/kizvpgXQfrAgN8FhOd87LbKk6kO.jpg,1989-08-11,A Nightmare on Elm Street: The Dream Child,False,5.420,1388
10,False,/ohqTNoA6pYzTXookp8UXNWQlAgY.jpg,[35],531949,en,Father of the Year,"Two college grads return to their hometown, wh...",0.8541,/mmBdCkZxHwQn5zM17cZmd3giJCY.jpg,2018-07-20,Father of the Year,False,5.419,488
11,False,/zKZqtGKmysHNbmsJQWS51rywROw.jpg,"[18, 53, 28, 878]",347882,en,Sleight,A young street magician is left to take care o...,3.0403,/eLk7yoWxK4S0xkV24YWoPKbIsbf.jpg,2016-04-28,Sleight,False,5.400,531
12,False,/7ANVSRoyytu28zGOSXafMk0WbZM.jpg,[53],340677,en,I.T.,"Mike Regan is a successful, self-made man who ...",1.2755,/A5VrX0pzM2pnPNXwKO3jKTt35ux.jpg,2016-09-09,I.T.,False,5.400,670
13,False,/xuA7vrQJ6aorU0lpenN13Jk9eIz.jpg,"[27, 878]",254191,en,Honeymoon,"On her honeymoon, a young bride sleepwalks int...",6.0307,/8XPGgvhsJxFvmVH9xAm9q9J7Coy.jpg,2014-09-12,Honeymoon,False,5.419,618
14,False,/hgP1lEgyxFFhU607nqn0FHmG859.jpg,"[27, 53]",58428,en,The Innkeepers,During the final days at the Yankee Pedlar Inn...,5.3519,/aC9XHtf0Opw2IJDVjSkL8eO71An.jpg,2011-08-18,The Innkeepers,False,5.419,700
15,False,/lj7enxOyRXazcCIFJyCn9dLuF2V.jpg,"[35, 80, 9648]",338964,en,Bad Santa 2,"Fueled by cheap whiskey, greed and hatred, Wil...",1.4183,/xmsEwpA2fSq6IO3sfKrLuIPLHSc.jpg,2016-11-23,Bad Santa 2,False,5.418,857
16,False,/aMUBgI9LyeX4QJ5Y1cizPFPpAYD.jpg,"[35, 80, 18]",16991,en,Observe and Report,Mall security guard Ronnie Barnhardt is called...,1.0851,/zHuouWUKlRK0SeIjzTlmtoPLrFA.jpg,2009-04-10,Observe and Report,False,5.421,730
17,False,/AF0PiDItegyUtlBGDMGlSQbtro.jpg,"[35, 27]",43593,en,Piranha 3D,Each year the population of sleepy Lake Victor...,3.5332,/lMLS2OFBbNYMSB1ZbVp4q2S4zTU.jpg,2010-08-20,Piranha 3D,False,5.416,2346
18,False,/6epafgrlSnOJrNakHgY7pbYr513.jpg,[35],19794,en,Labor Pains,A young woman pretends to be pregnant in order...,0.8424,/mIjFpM6pPaGAXSaf2rhvxdj9uhV.jpg,2009-06-19,Labor Pains,False,5.416,447
19,False,/gIhLlTYILo2BP6xt2KeBNxQDN4E.jpg,"[12, 35, 10751, 878]",11425,en,"Honey, We Shrunk Ourselves",The joke's on absent-minded scientist Wayne Sz...,1.6177,/nbU3UgIjxNTrSSe2gcOSGQjf55a.jpg,1997-07-01,"Honey, We Shrunk Ourselves",False,5.400,714

In [72]:
# Get more Movies Data through Pagination
# First import time module
import time

session = requests.Session()
session.headers.update(headers)

all_movies = []

for page in range(1, 534): 
    params = {
        "page": 1
    }
    # first 5 pages
    try:
        params["page"] = page
        response = session.get(url, headers=headers, params=params, timeout=10)
        response.raise_for_status()
        data = response.json()
        all_movies.extend(data["results"])

        print(f"Fetched page {page}")
        time.sleep(0.5)   # Sleep for 0.5
    except requests.exceptions.RequestException as e:
        print(f"Error on page {page}: {e}")
        break

print("Total movies fetched:", len(all_movies))

Fetched page 1
Fetched page 2
Fetched page 3
Fetched page 4
Fetched page 5
Fetched page 6
Fetched page 7
Fetched page 8
Fetched page 9
Fetched page 10
Fetched page 11
Fetched page 12
Fetched page 13
Fetched page 14
Fetched page 15
Fetched page 16
Fetched page 17
Fetched page 18
Fetched page 19
Fetched page 20
Fetched page 21
Fetched page 22
Fetched page 23
Fetched page 24
Fetched page 25
Fetched page 26
Fetched page 27
Fetched page 28
Fetched page 29
Fetched page 30
Fetched page 31
Fetched page 32
Fetched page 33
Fetched page 34
Fetched page 35
Fetched page 36
Fetched page 37
Fetched page 38
Fetched page 39
Fetched page 40
Fetched page 41
Fetched page 42
Fetched page 43
Fetched page 44
Fetched page 45
Fetched page 46
Fetched page 47
Fetched page 48
Fetched page 49
Fetched page 50
Fetched page 51
Fetched page 52
Fetched page 53
Fetched page 54
Fetched page 55
Fetched page 56
Fetched page 57
Fetched page 58
Fetched page 59
Fetched page 60
Fetched page 61
Fetched page 62
Fetched page 63
Fetched page 64
Fetched page 65
Fetched page 66
Fetched page 67
Fetched page 68
Fetched page 69
Fetched page 70
Fetched page 71
Fetched page 72
Fetched page 73
Fetched page 74
Fetched page 75
Fetched page 76
Fetched page 77
Fetched page 78
Fetched page 79
Fetched page 80
Fetched page 81
Fetched page 82
Fetched page 83
Fetched page 84
Fetched page 85
Fetched page 86
Fetched page 87
Fetched page 88
Fetched page 89
Fetched page 90
Fetched page 91
Fetched page 92
Fetched page 93
Fetched page 94
Fetched page 95
Fetched page 96
Fetched page 97
Fetched page 98
Fetched page 99
Fetched page 100
Fetched page 101
Fetched page 102
Fetched page 103
Fetched page 104
Fetched page 105
Fetched page 106
Fetched page 107
Fetched page 108
Fetched page 109
Fetched page 110
Fetched page 111
Fetched page 112
Fetched page 113
Fetched page 114
Fetched page 115
Fetched page 116
Fetched page 117
Fetched page 118
Fetched page 119
Fetched page 120
Fetched page 121
Fetched page 122
Fetched page 123
Fetched page 124
Fetched page 125
Fetched page 126
Fetched page 127
Fetched page 128
Fetched page 129
Fetched page 130
Fetched page 131
Fetched page 132
Fetched page 133
Fetched page 134
Fetched page 135
Fetched page 136
Fetched page 137
Fetched page 138
Fetched page 139
Fetched page 140
Fetched page 141
Fetched page 142
Fetched page 143
Fetched page 144
Fetched page 145
Fetched page 146
Fetched page 147
Fetched page 148
Fetched page 149
Fetched page 150
Fetched page 151
Fetched page 152
Fetched page 153
Fetched page 154
Fetched page 155
Fetched page 156
Fetched page 157
Fetched page 158
Fetched page 159
Fetched page 160
Fetched page 161
Fetched page 162
Fetched page 163
Fetched page 164
Fetched page 165
Fetched page 166
Fetched page 167
Fetched page 168
Fetched page 169
Fetched page 170
Fetched page 171
Fetched page 172
Fetched page 173
Fetched page 174
Fetched page 175
Fetched page 176
Fetched page 177
Fetched page 178
Fetched page 179
Fetched page 180
Fetched page 181
Fetched page 182
Fetched page 183
Fetched page 184
Fetched page 185
Fetched page 186
Fetched page 187
Fetched page 188
Fetched page 189
Fetched page 190
Fetched page 191
Fetched page 192
Fetched page 193
Fetched page 194
Fetched page 195
Fetched page 196
Fetched page 197
Fetched page 198
Fetched page 199
Fetched page 200
Fetched page 201
Fetched page 202
Fetched page 203
Fetched page 204
Fetched page 205
Fetched page 206
Fetched page 207
Fetched page 208
Fetched page 209
Fetched page 210
Fetched page 211
Fetched page 212
Fetched page 213
Fetched page 214
Fetched page 215
Fetched page 216
Fetched page 217
Fetched page 218
Fetched page 219
Fetched page 220
Fetched page 221
Fetched page 222
Fetched page 223
Fetched page 224
Fetched page 225
Fetched page 226
Fetched page 227
Fetched page 228
Fetched page 229
Fetched page 230
Fetched page 231
Fetched page 232
Fetched page 233
Fetched page 234
Fetched page 235
Fetched page 236
Fetched page 237
Fetched page 238
Fetched page 239
Fetched page 240
Fetched page 241
Fetched page 242
Fetched page 243
Fetched page 244
Fetched page 245
Fetched page 246
Fetched page 247
Fetched page 248
Fetched page 249
Fetched page 250
Fetched page 251
Fetched page 252
Fetched page 253
Fetched page 254
Fetched page 255
Fetched page 256
Fetched page 257
Fetched page 258
Fetched page 259
Fetched page 260
Fetched page 261
Fetched page 262
Fetched page 263
Fetched page 264
Fetched page 265
Fetched page 266
Fetched page 267
Fetched page 268
Fetched page 269
Fetched page 270
Fetched page 271
Fetched page 272
Fetched page 273
Fetched page 274
Fetched page 275
Fetched page 276
Fetched page 277
Fetched page 278
Fetched page 279
Fetched page 280
Fetched page 281
Fetched page 282
Fetched page 283
Fetched page 284
Fetched page 285
Fetched page 286
Fetched page 287
Fetched page 288
Fetched page 289
Fetched page 290
Fetched page 291
Fetched page 292
Fetched page 293
Fetched page 294
Fetched page 295
Fetched page 296
Fetched page 297
Fetched page 298
Fetched page 299
Fetched page 300
Fetched page 301
Fetched page 302
Fetched page 303
Fetched page 304
Fetched page 305
Fetched page 306
Fetched page 307
Fetched page 308
Fetched page 309
Fetched page 310
Fetched page 311
Fetched page 312
Fetched page 313
Fetched page 314
Fetched page 315
Fetched page 316
Fetched page 317
Fetched page 318
Fetched page 319
Fetched page 320
Fetched page 321
Fetched page 322
Fetched page 323
Fetched page 324
Fetched page 325
Fetched page 326
Fetched page 327
Fetched page 328
Fetched page 329
Fetched page 330
Fetched page 331
Fetched page 332
Fetched page 333
Fetched page 334
Fetched page 335
Fetched page 336
Fetched page 337
Fetched page 338
Fetched page 339
Fetched page 340
Fetched page 341
Fetched page 342
Fetched page 343
Fetched page 344
Fetched page 345
Fetched page 346
Fetched page 347
Fetched page 348
Fetched page 349
Fetched page 350
Fetched page 351
Fetched page 352
Fetched page 353
Fetched page 354
Fetched page 355
Fetched page 356
Fetched page 357
Fetched page 358
Fetched page 359
Fetched page 360
Fetched page 361
Fetched page 362
Fetched page 363
Fetched page 364
Fetched page 365
Fetched page 366
Fetched page 367
Fetched page 368
Fetched page 369
Fetched page 370
Fetched page 371
Fetched page 372
Fetched page 373
Fetched page 374
Fetched page 375
Fetched page 376
Fetched page 377
Fetched page 378
Fetched page 379
Fetched page 380
Fetched page 381
Fetched page 382
Fetched page 383
Fetched page 384
Fetched page 385
Fetched page 386
Fetched page 387
Fetched page 388
Fetched page 389
Fetched page 390
Fetched page 391
Fetched page 392
Fetched page 393
Fetched page 394
Fetched page 395
Fetched page 396
Fetched page 397
Fetched page 398
Fetched page 399
Fetched page 400
Fetched page 401
Fetched page 402
Fetched page 403
Fetched page 404
Fetched page 405
Fetched page 406
Fetched page 407
Fetched page 408
Fetched page 409
Fetched page 410
Fetched page 411
Fetched page 412
Fetched page 413
Fetched page 414
Fetched page 415
Fetched page 416
Fetched page 417
Fetched page 418
Fetched page 419
Fetched page 420
Fetched page 421
Fetched page 422
Fetched page 423
Fetched page 424
Fetched page 425
Fetched page 426
Fetched page 427
Fetched page 428
Fetched page 429
Fetched page 430
Fetched page 431
Fetched page 432
Fetched page 433
Fetched page 434
Fetched page 435
Fetched page 436
Fetched page 437
Fetched page 438
Fetched page 439
Fetched page 440
Fetched page 441
Fetched page 442
Fetched page 443
Fetched page 444
Fetched page 445
Fetched page 446
Fetched page 447
Fetched page 448
Fetched page 449
Fetched page 450
Fetched page 451
Fetched page 452
Fetched page 453
Fetched page 454
Fetched page 455
Fetched page 456
Fetched page 457
Fetched page 458
Fetched page 459
Fetched page 460
Fetched page 461
Fetched page 462
Fetched page 463
Fetched page 464
Fetched page 465
Fetched page 466
Fetched page 467
Fetched page 468
Fetched page 469
Fetched page 470
Fetched page 471
Fetched page 472
Fetched page 473
Fetched page 474
Fetched page 475
Fetched page 476
Fetched page 477
Fetched page 478
Fetched page 479
Fetched page 480
Fetched page 481
Fetched page 482
Fetched page 483
Fetched page 484
Fetched page 485
Fetched page 486
Fetched page 487
Fetched page 488
Fetched page 489
Fetched page 490
Fetched page 491
Fetched page 492
Fetched page 493
Fetched page 494
Fetched page 495
Fetched page 496
Fetched page 497
Fetched page 498
Fetched page 499
Fetched page 500
Error on page 501: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?page=501
Total movies fetched: 10000

In [89]:
movies = pd.DataFrame(all_movies)
movies.to_csv('movies_data.csv', index=False)

In [129]:
# read_csv() file
df = pd.read_csv('movies_data.csv')
df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,29.0492,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.715,29668
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",29.2045,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.687,22412
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,17.4914,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.571,13556
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,15.2937,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.566,17075
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,11.5948,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.554,9717
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,/lj7enxOyRXazcCIFJyCn9dLuF2V.jpg,"[35, 80, 9648]",338964,en,Bad Santa 2,"Fueled by cheap whiskey, greed and hatred, Wil...",1.4183,/xmsEwpA2fSq6IO3sfKrLuIPLHSc.jpg,2016-11-23,Bad Santa 2,False,5.418,857
9996,False,/aMUBgI9LyeX4QJ5Y1cizPFPpAYD.jpg,"[35, 80, 18]",16991,en,Observe and Report,Mall security guard Ronnie Barnhardt is called...,1.0851,/zHuouWUKlRK0SeIjzTlmtoPLrFA.jpg,2009-04-10,Observe and Report,False,5.421,730
9997,False,/AF0PiDItegyUtlBGDMGlSQbtro.jpg,"[35, 27]",43593,en,Piranha 3D,Each year the population of sleepy Lake Victor...,3.5332,/lMLS2OFBbNYMSB1ZbVp4q2S4zTU.jpg,2010-08-20,Piranha 3D,False,5.416,2346
9998,False,/6epafgrlSnOJrNakHgY7pbYr513.jpg,[35],19794,en,Labor Pains,A young woman pretends to be pregnant in order...,0.8424,/mIjFpM6pPaGAXSaf2rhvxdj9uhV.jpg,2009-06-19,Labor Pains,False,5.416,447
9999,False,/gIhLlTYILo2BP6xt2KeBNxQDN4E.jpg,"[12, 35, 10751, 878]",11425,en,"Honey, We Shrunk Ourselves",The joke's on absent-minded scientist Wayne Sz...,1.6177,/nbU3UgIjxNTrSSe2gcOSGQjf55a.jpg,1997-07-01,"Honey, We Shrunk Ourselves",False,5.400,714

In [107]:
# fancy indexing
# boolean indexing
df[df['backdrop_path'].isna()].shape

(13, 14)

In [132]:
# import new upcoming movies data

import requests

new_url = "https://api.themoviedb.org/3/movie/upcoming?language=en-US&page=1"
headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwNWM3NWY1MjNkYzYyZmFiNzVhNjJmYTc1MGM1NWEzMSIsIm5iZiI6MTc3MDM5MzIzMy42Mywic3ViIjoiNjk4NjBlOTFmMmU5NzU0YWI0NDhkZTJiIiwic2NvcGVzIjpbImFwaV9yZWFkIl0sInZlcnNpb24iOjF9.xze-JgRv5x5MhGWkMknwVIKVy_0vBD1-byIpdfI5f2I"
}

response = requests.get(new_url, headers=headers)

data = response.json()

In [133]:
# Let it convert into the DataFrame
new_movies = data['results']
pd.DataFrame(new_movies).head(1)

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/tyjXlexbNZQ0ZT1KEJslQtBirqc.jpg,"[12, 53, 878]",840464,en,Greenland 2: Migration,Having found the safety of the Greenland bunke...,515.6229,/z2tqCJLsw6uEJ8nJV8BsQXGa3dr.jpg,2026-01-07,Greenland 2: Migration,False,6.528,338

In [134]:
# Get more Movies Data through Pagination
# importing time module
import time
session = requests.Session()
session.headers.update(headers)

all_movies = []

for page in range(1, 534): 
    params = {
        "page": 1
    }
    # try 
    try:
        params["page"] = page
        response = session.get(new_url, headers=headers, params=params, timeout=10)
        response.raise_for_status()
        data = response.json()
        all_movies.extend(data["results"])

        print(f"Fetched page {page}")
        time.sleep(0.5)   # Sleep for 0.5
    # except
    except requests.exceptions.RequestException as e:
        print(f"Error on page {page}: {e}")
        break

print("Total movies fetched:", len(all_movies))

Fetched page 1
Fetched page 2
Fetched page 3
Fetched page 4
Fetched page 5
Fetched page 6
Fetched page 7
Fetched page 8
Fetched page 9
Fetched page 10
Fetched page 11
Fetched page 12
Fetched page 13
Fetched page 14
Fetched page 15
Fetched page 16
Fetched page 17
Fetched page 18
Fetched page 19
Fetched page 20
Fetched page 21
Fetched page 22
Fetched page 23
Fetched page 24
Fetched page 25
Fetched page 26
Fetched page 27
Fetched page 28
Fetched page 29
Fetched page 30
Fetched page 31
Fetched page 32
Fetched page 33
Fetched page 34
Fetched page 35
Fetched page 36
Fetched page 37
Fetched page 38
Fetched page 39
Fetched page 40
Fetched page 41
Fetched page 42
Fetched page 43
Fetched page 44
Fetched page 45
Fetched page 46
Fetched page 47
Fetched page 48
Fetched page 49
Fetched page 50
Fetched page 51
Fetched page 52
Fetched page 53
Fetched page 54
Fetched page 55
Fetched page 56
Fetched page 57
Fetched page 58
Fetched page 59
Fetched page 60
Fetched page 61
Fetched page 62
Fetched page 63
Fetched page 64
Fetched page 65
Fetched page 66
Fetched page 67
Fetched page 68
Fetched page 69
Fetched page 70
Fetched page 71
Fetched page 72
Fetched page 73
Fetched page 74
Fetched page 75
Fetched page 76
Fetched page 77
Fetched page 78
Fetched page 79
Fetched page 80
Fetched page 81
Fetched page 82
Fetched page 83
Fetched page 84
Fetched page 85
Fetched page 86
Fetched page 87
Fetched page 88
Fetched page 89
Fetched page 90
Fetched page 91
Fetched page 92
Fetched page 93
Fetched page 94
Fetched page 95
Fetched page 96
Fetched page 97
Fetched page 98
Fetched page 99
Fetched page 100
Fetched page 101
Fetched page 102
Fetched page 103
Fetched page 104
Fetched page 105
Fetched page 106
Fetched page 107
Fetched page 108
Fetched page 109
Fetched page 110
Fetched page 111
Fetched page 112
Fetched page 113
Fetched page 114
Fetched page 115
Fetched page 116
Fetched page 117
Fetched page 118
Fetched page 119
Fetched page 120
Fetched page 121
Fetched page 122
Fetched page 123
Fetched page 124
Fetched page 125
Fetched page 126
Fetched page 127
Fetched page 128
Fetched page 129
Fetched page 130
Fetched page 131
Fetched page 132
Fetched page 133
Fetched page 134
Fetched page 135
Fetched page 136
Fetched page 137
Fetched page 138
Fetched page 139
Fetched page 140
Fetched page 141
Fetched page 142
Fetched page 143
Fetched page 144
Fetched page 145
Fetched page 146
Fetched page 147
Fetched page 148
Fetched page 149
Fetched page 150
Fetched page 151
Fetched page 152
Fetched page 153
Fetched page 154
Fetched page 155
Fetched page 156
Fetched page 157
Fetched page 158
Fetched page 159
Fetched page 160
Fetched page 161
Fetched page 162
Fetched page 163
Fetched page 164
Fetched page 165
Fetched page 166
Fetched page 167
Fetched page 168
Fetched page 169
Fetched page 170
Fetched page 171
Fetched page 172
Fetched page 173
Fetched page 174
Fetched page 175
Fetched page 176
Fetched page 177
Fetched page 178
Fetched page 179
Fetched page 180
Fetched page 181
Fetched page 182
Fetched page 183
Fetched page 184
Fetched page 185
Fetched page 186
Fetched page 187
Fetched page 188
Fetched page 189
Fetched page 190
Fetched page 191
Fetched page 192
Fetched page 193
Fetched page 194
Fetched page 195
Fetched page 196
Fetched page 197
Fetched page 198
Fetched page 199
Fetched page 200
Fetched page 201
Fetched page 202
Fetched page 203
Fetched page 204
Fetched page 205
Fetched page 206
Fetched page 207
Fetched page 208
Fetched page 209
Fetched page 210
Fetched page 211
Fetched page 212
Fetched page 213
Fetched page 214
Fetched page 215
Fetched page 216
Fetched page 217
Fetched page 218
Fetched page 219
Fetched page 220
Fetched page 221
Fetched page 222
Fetched page 223
Fetched page 224
Fetched page 225
Fetched page 226
Fetched page 227
Fetched page 228
Fetched page 229
Fetched page 230
Fetched page 231
Fetched page 232
Fetched page 233
Fetched page 234
Fetched page 235
Fetched page 236
Fetched page 237
Fetched page 238
Fetched page 239
Fetched page 240
Fetched page 241
Fetched page 242
Fetched page 243
Fetched page 244
Fetched page 245
Fetched page 246
Fetched page 247
Fetched page 248
Fetched page 249
Fetched page 250
Fetched page 251
Fetched page 252
Fetched page 253
Fetched page 254
Fetched page 255
Fetched page 256
Fetched page 257
Fetched page 258
Fetched page 259
Fetched page 260
Fetched page 261
Fetched page 262
Fetched page 263
Fetched page 264
Fetched page 265
Fetched page 266
Fetched page 267
Fetched page 268
Fetched page 269
Fetched page 270
Fetched page 271
Fetched page 272
Fetched page 273
Fetched page 274
Fetched page 275
Fetched page 276
Fetched page 277
Fetched page 278
Fetched page 279
Fetched page 280
Fetched page 281
Fetched page 282
Fetched page 283
Fetched page 284
Fetched page 285
Fetched page 286
Fetched page 287
Fetched page 288
Fetched page 289
Fetched page 290
Fetched page 291
Fetched page 292
Fetched page 293
Fetched page 294
Fetched page 295
Fetched page 296
Fetched page 297
Fetched page 298
Fetched page 299
Fetched page 300
Fetched page 301
Fetched page 302
Fetched page 303
Fetched page 304
Fetched page 305
Fetched page 306
Fetched page 307
Fetched page 308
Fetched page 309
Fetched page 310
Fetched page 311
Fetched page 312
Fetched page 313
Fetched page 314
Fetched page 315
Fetched page 316
Fetched page 317
Fetched page 318
Fetched page 319
Fetched page 320
Fetched page 321
Fetched page 322
Fetched page 323
Fetched page 324
Fetched page 325
Fetched page 326
Fetched page 327
Fetched page 328
Fetched page 329
Fetched page 330
Fetched page 331
Fetched page 332
Fetched page 333
Fetched page 334
Fetched page 335
Fetched page 336
Fetched page 337
Fetched page 338
Fetched page 339
Fetched page 340
Fetched page 341
Fetched page 342
Fetched page 343
Fetched page 344
Fetched page 345
Fetched page 346
Fetched page 347
Fetched page 348
Fetched page 349
Fetched page 350
Fetched page 351
Fetched page 352
Fetched page 353
Fetched page 354
Fetched page 355
Fetched page 356
Fetched page 357
Fetched page 358
Fetched page 359
Fetched page 360
Fetched page 361
Fetched page 362
Fetched page 363
Fetched page 364
Fetched page 365
Fetched page 366
Fetched page 367
Fetched page 368
Fetched page 369
Fetched page 370
Fetched page 371
Fetched page 372
Fetched page 373
Fetched page 374
Fetched page 375
Fetched page 376
Fetched page 377
Fetched page 378
Fetched page 379
Fetched page 380
Fetched page 381
Fetched page 382
Fetched page 383
Fetched page 384
Fetched page 385
Fetched page 386
Fetched page 387
Fetched page 388
Fetched page 389
Fetched page 390
Fetched page 391
Fetched page 392
Fetched page 393
Fetched page 394
Fetched page 395
Fetched page 396
Fetched page 397
Fetched page 398
Fetched page 399
Fetched page 400
Fetched page 401
Fetched page 402
Fetched page 403
Fetched page 404
Fetched page 405
Fetched page 406
Fetched page 407
Fetched page 408
Fetched page 409
Fetched page 410
Fetched page 411
Fetched page 412
Fetched page 413
Fetched page 414
Fetched page 415
Fetched page 416
Fetched page 417
Fetched page 418
Fetched page 419
Fetched page 420
Fetched page 421
Fetched page 422
Fetched page 423
Fetched page 424
Fetched page 425
Fetched page 426
Fetched page 427
Fetched page 428
Fetched page 429
Fetched page 430
Fetched page 431
Fetched page 432
Fetched page 433
Fetched page 434
Fetched page 435
Fetched page 436
Fetched page 437
Fetched page 438
Fetched page 439
Fetched page 440
Fetched page 441
Fetched page 442
Fetched page 443
Fetched page 444
Fetched page 445
Fetched page 446
Fetched page 447
Fetched page 448
Fetched page 449
Fetched page 450
Fetched page 451
Fetched page 452
Fetched page 453
Fetched page 454
Fetched page 455
Fetched page 456
Fetched page 457
Fetched page 458
Fetched page 459
Fetched page 460
Fetched page 461
Fetched page 462
Fetched page 463
Fetched page 464
Fetched page 465
Fetched page 466
Fetched page 467
Fetched page 468
Fetched page 469
Fetched page 470
Fetched page 471
Fetched page 472
Fetched page 473
Fetched page 474
Fetched page 475
Fetched page 476
Fetched page 477
Fetched page 478
Fetched page 479
Fetched page 480
Fetched page 481
Fetched page 482
Fetched page 483
Fetched page 484
Fetched page 485
Fetched page 486
Fetched page 487
Fetched page 488
Fetched page 489
Fetched page 490
Fetched page 491
Fetched page 492
Fetched page 493
Fetched page 494
Fetched page 495
Fetched page 496
Fetched page 497
Fetched page 498
Fetched page 499
Fetched page 500
Error on page 501: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/upcoming?language=en-US&page=1&page=501
Total movies fetched: 1022

In [139]:
new_movies = pd.DataFrame(all_movies)
new_movies.to_csv('new_movies.csv', index=False)

In [142]:
pd.read_csv('new_movies.csv').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1022 entries, 0 to 1021
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adult              1022 non-null   bool
 1   backdrop_path      595 non-null    object
 2   genre_ids          1022 non-null   object
 3   id                 1022 non-null   int64
 4   original_language  1022 non-null   object
 5   original_title     1022 non-null   object
 6   overview           917 non-null    object
 7   popularity         1022 non-null   float64
 8   poster_path        865 non-null    object
 9   release_date       1021 non-null   object
 10  title              1022 non-null   object
 11  video              1022 non-null   bool
 12  vote_average       1022 non-null   float64
 13  vote_count         1022 non-null   int64
dtypes: bool(2), float64(2), int64(2), object(8)
memory usage: 97.9+ KB

In [143]:
pd.read_csv('movies_data.csv').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adult              10000 non-null  bool
 1   backdrop_path      9987 non-null   object
 2   genre_ids          10000 non-null  object
 3   id                 10000 non-null  int64
 4   original_language  10000 non-null  object
 5   original_title     10000 non-null  object
 6   overview           9998 non-null   object
 7   popularity         10000 non-null  float64
 8   poster_path        9993 non-null   object
 9   release_date       9997 non-null   object
 10  title              10000 non-null  object
 11  video              10000 non-null  bool
 12  vote_average       10000 non-null  float64
 13  vote_count         10000 non-null  int64
dtypes: bool(2), float64(2), int64(2), object(8)
memory usage: 957.2+ KB