In [2]:
# import libraries
import numpy as np
import pandas as pd

In [3]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
time.info() #

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

## *Working With Dates*

In [14]:
# Converting to 'datetime' datatype
date['date'] = pd.to_datetime(date['date'])
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

## 1. *Extract Year*

In [17]:
date['date_year'] = date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
453 2019-12-13        3860       22       1       2019
856 2019-10-18        4594       22       6       2019
53  2019-12-04        5193       16       2       2019
527 2019-08-01        2811       13       2       2019
565 2019-04-29         888       20       5       2019

## 2. *Extract Month*

In [27]:
date['date_month'] = date['date'].dt.month
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow
690,2018-12-16,3799,20,3,2018,12,December,16,6
929,2019-12-07,6801,3,7,2019,12,December,7,5
509,2019-07-10,7269,30,2,2019,7,July,10,2
830,2019-03-14,3047,4,4,2019,3,March,14,3
492,2019-06-24,2306,14,12,2019,6,June,24,0

In [28]:
date['date_month_name'] = date['date'].dt.month_name()
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow
72,2018-08-27,7582,17,30,2018,8,August,27,0
650,2019-05-21,5626,22,1,2019,5,May,21,1
928,2019-01-02,5371,22,4,2019,1,January,2,2
878,2019-04-30,7510,16,5,2019,4,April,30,1
913,2019-03-08,2668,16,1,2019,3,March,8,4

## 3. *Extract Days*

In [29]:
date['date_day'] = date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [30]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [32]:
# day of week_name
date['date_dow_name'] = date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

In [33]:
# is weekend?
# day of week
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1, 0)

date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

## *Extract Week of the year*

In [38]:
# extract week of the year
date['date_week'] = date['date'].dt.isocalendar().week
# drop columns
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

## *Extract Quarter*

In [39]:
date['quarter'] = date['date'].dt.quarter
# drop columns
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

## *Extract Semester*

In [40]:
date['quarter'] = np.where(date['quarter'].isin([1,2]), 1, 0)
# drop columns
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,0
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,0
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

## *Extract Time elapsed between dates*

In [41]:
import datetime

today = datetime.datetime.today()
today

datetime.datetime(2026, 4, 30, 17, 41, 35, 137250)

In [45]:
(today-date['date']).dt.days

0      2333
1      2815
2      2746
3      2448
4      2671
       ...
995    2761
996    2702
997    2550
998    2615
999    2389
Name: date, Length: 1000, dtype: int64

In [50]:
# Month passed
np.round((today - date['date'])/np.timedelta64(1, 'm'), 0)

0      3360582.0
1      4054662.0
2      3955302.0
3      3526182.0
4      3847302.0
         ...
995    3976902.0
996    3891942.0
997    3673062.0
998    3766662.0
999    3441222.0
Name: date, Length: 1000, dtype: float64

## *Time*

In [57]:
# Check info for the time
time.info()
# change Dtype of date column
time['date'] = pd.to_datetime(time['date'])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [59]:
# extract hour
time['hour'] = time['date'].dt.hour
# extract minute
time['min'] = time['date'].dt.minute
# extract second
time['sec'] = time['date'].dt.second

In [61]:
time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0